sauce_connect: true
browsers:
  - name: chrome
    version: 39..latest
  - name: firefox
    version: 34..latest
  - name: safari
    version: 7..latest
  - name: microsoftedge
    version: 13..latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: '8.1..latest'
  - name: android
    version: '4.4..6.0' # TODO: change this back to latest once https://github.com/airtap/browsers/issues/3 is fixed
server: ./test/server/index.js
scripts:
  - "/ie8-polyfill.js"
  - "/test-polyfill.js"
